export const FETCH_HALL_JOB = 'FETCH_HALL_JOB';
export const FETCH_HALL_JOB_NEXT = 'FETCH_HALL_JOB_NEXT';
export const FETCH_HALL_TYPE = 'FETCH_HALL_TYPE';
export const FETCH_HALL_JOB_DETAIL = 'FETCH_HALL_JOB_DETAIL';
export const CLEAR_LIST = 'CLEAR_LIST';
export const HALL_SIGN_UP = 'HALL_SIGN_UP';
