export const FETCH_HOME_IMG = 'FETCH_HOME_IMG';
export const FETCH_HOME_SIGNIN = 'FETCH_HOME_SIGNIN';
export const HOME_SIGNIN = 'HOME_SIGNIN';
export const HOME_SIGNIN_RECOMMEND = 'HOME_SIGNIN_RECOMMEND';
